config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    root                            to: 'home#index'
    get 'index',                    to: 'home#index'
    resources :products,            only: [:index, :show]
    resources :categories,          only: [:show]
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
  end
  get '*not_found',                 to: 'application#routing_error'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/option_type_decorator.rb
Spree::OptionType.class_eval do
  scope :search_option_value, -> option_type { find_by(name: option_type).option_values }
end

app/models/spree/option_value_decorator.rb
Spree::OptionValue.class_eval do
  def eager_load_variants
    variants.includes(:default_price, :images)
  end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  scope :eager_load_products, -> { includes(master: [:default_price, :images]) }
  scope :related_products, -> product { includes(:taxons).where(spree_taxons: { id: product.taxons.ids }) }
  scope :exclude_product, -> product_id { where.not(id: product_id) }

  # 対象商品一覧取得
  def self.get_taxon_products(taxon)
    taxon_ids = taxon.leaf? ? taxon.id : taxon.leaves.ids
    eager_load_products.includes(:taxons).where(spree_products_taxons: { taxon_id: taxon_ids })
  end

  # 関連商品を取得
  def related_products(product, count)
    Spree::Product.eager_load_products.related_products(product).exclude_product(product.id).limit(count)
  end

  # 新着商品取得
  def self.new_arrivals(count)
    eager_load_products.available.order(available_on: :desc).limit(count)
  end
end

app/models/spree/taxon_decorator.rb
Spree::Taxon.class_eval do
  # 各カテゴリーの商品数取得
  def products_quantity
    return products.count if leaf?
    # category・Brandなど項目の商品数取得
    leaves.includes(:products).map { |l| l.products.count }.inject(:+)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # 例外処理
  unless Rails.env.development?
    rescue_from ActiveRecord::RecordNotFound,   with: :render_404
    rescue_from ActionController::RoutingError, with: :render_404
    rescue_from Exception,                      with: :render_500
  end

  def routing_error
    raise ActionController::RoutingError, params[:path]
  end

  private

  def render_404
    render file: Rails.root.join('public/404.html'), status: 404, layout: false, content_type: 'text/html'
  end

  def render_500
    render file: Rails.root.join('public/500.html'), status: 500, layout: false, content_type: 'text/html'
  end
end

app/controllers/concerns/sidebar.rb
module Sidebar
  def sidebar_search
    @taxonomies = Spree::Taxonomy.includes(:taxons)
    @search_colors = Spree::OptionType.search_option_value('tshirt-color')
  end
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  include Sidebar

  def show
    # 選択されたカテゴリーの取得
    @taxon = Spree::Taxon.find_by_id(params[:id])
    return routing_error unless @taxon
    sidebar_search
    # 対象商品一覧取得
    @products = Spree::Product.get_taxon_products(@taxon)
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  NEW_ARRIVALS_PRODUCTS_COUNT = 8
  def index
    # 新着商品取得
    @new_arrivals_products = Spree::Product.new_arrivals(NEW_ARRIVALS_PRODUCTS_COUNT)
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  RELATED_PRODUCTS_COUNT = 4
  include Sidebar

  def index
    @option_value_color = Spree::OptionValue.find_by(name: params[:color])
    sidebar_search
    products
  end

  def show
    @product = Spree::Product.find(params[:id])
    # 関連商品
    @related = @product.related_products(@product, RELATED_PRODUCTS_COUNT)
    @variant_number = params[:variant]
    variants
  end

  private

  def products
    if params[:color]
      return flash.now[:error] = "検索エラー.  別の方法で検索してください" if @option_value_color.nil?
      @products = @option_value_color.eager_load_variants
    else
      @products = Spree::Product.eager_load_products
    end
  end

  def variants
    unless @variant_number.nil?
      @variants = Spree::Variant.includes(:images).find(@variant_number)
    end
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  layout 'sample_application'

  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the complete title for each page.
  def full_title(page_title:)
    base_title = 'Potepanec'
    if page_title.empty?
      base_title
    else
      page_title
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def product_link(product)
    if product.respond_to?(:product_id)
      potepan_product_path(product.product_id, variant: product.id)
    else
      potepan_product_path(product.id)
    end
  end

  def product_main_image_active?(index, variant_number)
    return false unless variant_number.nil?
    index.zero?
  end

  def product_thumb_image_number(index, image_size)
    index + image_size
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= render 'shared/head' %>
  </head>
  <body>
    <div class="main-wrapper">
      <%= render 'shared/header' %>
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>

    <%= render 'shared/login_modal' %>
    <%= render 'shared/sign_up_modal' %>
    <%= yield :product_quick_view_modal %>
    <%= render 'shared/script' %>
  </body>
</html>

app/views/layouts/sample_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Potepanec</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/potepan/categories/_filter.html.erb
<div class="row filterArea">
  <div class="col-xs-6">
    <select name="guiest_id1" id="guiest_id1" class="select-drop">
      <option value="0">並び替え</option>
      <option value="1">人気順</option>
      <option value="2">安い順</option>
      <option value="3">新着順</option>
      <option value="3">高い順</option>
    </select>
  </div>
  <div class="col-xs-6">
    <div class="btn-group pull-right" role="group">
      <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'">
        <i class="fa fa-th" aria-hidden="true"></i>
        <span>Grid</span>
      </button>
      <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'">
        <i class="fa fa-th-list" aria-hidden="true"></i>
        <span>List</span>
      </button>
    </div>
  </div>
</div>

app/views/potepan/categories/_sidebar.html.erb
<div class="col-md-3 col-sm-4 col-xs-12 sideBar">
  <%= render 'shared/sidebar_categories', taxonomies: @taxonomies, active_taxon_id: @taxon.id %>
  <%= render 'shared/sidebar_search_price' %>
  <%= render 'shared/sidebar_search_color', search_colors: @search_colors, active_color_name: nil %>
  <%= render 'shared/sidebar_search_size' %>
</div>

app/views/potepan/categories/show.html.erb
<% provide(:title, 'Product Grid Sidebar Left - BIGBAG Store') %>
<%= render partial: 'shared/main_nav_bar', locals: { page_title: @taxon.name,
                                                     path_second: true,
                                                     page_active: @taxon.name } %>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <%= render 'potepan/categories/sidebar' %>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <%= render 'potepan/categories/filter' %>
        <div class="row">
          <%= render partial: 'shared/product', collection: @products, locals: { class_name: 'col-sm-4 col-xs-12' } %>
        </div>
      </div>
    </div>
  </div>
</section>

<%= render 'shared/partners_logo' %>

<% content_for :product_quick_view_modal do %>
  <%= render 'shared/product_quick_view_modal'%>
<% end %>

app/views/potepan/home/_banner.html.erb
<div class="bannercontainer">
  <div class="fullscreenbanner-container">
    <div class="fullscreenbanner">
      <ul>
        <li data-transition="slidehorizontal" data-slotamount="5" data-masterspeed="700" data-title="Slide 1">
          <%= image_tag("home/banner-slider/slider-bg.jpg", :alt => "slidebg1", data:{bgposition: "center center", bgfit: "cover" , bgrepeat: "no-repeat"}) %>
          <div class="slider-caption container">
            <div class="tp-caption rs-caption-1 sft start"
              data-hoffset="0"
              data-x="370"
              data-y="54"
              data-speed="800"
              data-start="1500"
              data-easing="Back.easeInOut"
              data-endspeed="300">
              <%= image_tag("home/banner-slider/shoe1.png", :alt => "slider-image") %>
            </div>

            <div class="tp-caption rs-caption-2 sft"
              data-hoffset="0"
              data-y="119"
              data-speed="800"
              data-start="2000"
              data-easing="Back.easeInOut"
              data-endspeed="300">
              Canvas Sneaker
            </div>

            <div class="tp-caption rs-caption-3 sft"
              data-hoffset="0"
              data-y="185"
              data-speed="1000"
              data-start="3000"
              data-easing="Power4.easeOut"
              data-endspeed="300"
              data-endeasing="Power1.easeIn"
              data-captionhidden="off">
              Exclusive to <br>
              BigBag <br>
              <small>Spring / Summer 2020</small>
            </div>
            <div class="tp-caption rs-caption-4 sft"
              data-hoffset="0"
              data-y="320"
              data-speed="800"
              data-start="3500"
              data-easing="Power4.easeOut"
              data-endspeed="300"
              data-endeasing="Power1.easeIn"
              data-captionhidden="off">
              <span class="page-scroll"><a href="single_product.html" class="btn primary-btn">Buy Now<i class="glyphicon glyphicon-chevron-right"></i></a></span>
            </div>
          </div>
        </li>
        <li data-transition="slidehorizontal" data-slotamount="5" data-masterspeed="1000" data-title="Slide 2">
          <%= image_tag("home/banner-slider/slider-bg.jpg", :alt => "slidebg", data:{bgposition: "center center", bgfit: "cover" , bgrepeat: "no-repeat"}) %>
          <div class="slider-caption container captionCenter">
            <div class="tp-caption rs-caption-1 sft start captionCenterAlign"
              data-x="center"
              data-y="228"
              data-speed="800"
              data-start="1500"
              data-easing="Back.easeInOut"
              data-endspeed="300">
              <%= image_tag("home/banner-slider/shoe2.png", :alt => "slider-image") %>
            </div>

            <div class="tp-caption rs-caption-2 sft captionCenterAlign"
              data-x="center"
              data-y="50"
              data-speed="800"
              data-start="2000"
              data-easing="Back.easeInOut"
              data-endspeed="300">
              Exclusive to BigBag
            </div>

            <div class="tp-caption rs-caption-3 sft captionCenterAlign"
              data-x="center"
              data-y="98"
              data-speed="1000"
              data-start="3000"
              data-easing="Power4.easeOut"
              data-endspeed="300"
              data-endeasing="Power1.easeIn"
              data-captionhidden="off">
              Canvas Sneaker
            </div>

            <div class="tp-caption rs-caption-4 sft captionCenterAlign"
              data-x="center"
              data-y="156"
              data-speed="800"
              data-start="3500"
              data-easing="Power4.easeOut"
              data-endspeed="300"
              data-endeasing="Power1.easeIn"
              data-captionhidden="off">
              <span class="page-scroll"><a href="single_product.html" class="btn primary-btn">Buy Now<i class="glyphicon glyphicon-chevron-right"></i></a></span>
            </div>
          </div>
        </li>
        <li data-transition="slidehorizontal" data-slotamount="5" data-masterspeed="700"  data-title="Slide 3">
          <%= image_tag("home/banner-slider/slider-bg.jpg", :alt => "slidebg", data:{bgposition: "center center", bgfit: "cover" , bgrepeat: "no-repeat"}) %>
          <div class="slider-caption container">
            <div class="tp-caption rs-caption-1 sft start"
              data-hoffset="0"
              data-x="0"
              data-y="85"
              data-speed="800"
              data-start="1500"
              data-easing="Back.easeInOut"
              data-endspeed="300">
              <%= image_tag("home/banner-slider/shoe3.png", :alt => "slider-image") %>
            </div>

            <div class="tp-caption rs-caption-2 sft "
              data-hoffset="0"
              data-y="119"
              data-x="800"
              data-speed="800"
              data-start="2000"
              data-easing="Back.easeInOut"
              data-endspeed="300">
              Canvas Sneaker
            </div>

            <div class="tp-caption rs-caption-3 sft"
              data-hoffset="0"
              data-y="185"
              data-x="800"
              data-speed="1000"
              data-start="3000"
              data-easing="Power4.easeOut"
              data-endspeed="300"
              data-endeasing="Power1.easeIn"
              data-captionhidden="off">
              Exclusive to <br>
              BigBag <br>
              <small>Spring / Summer 2020</small>
            </div>

            <div class="tp-caption rs-caption-4 sft"
              data-hoffset="0"
              data-y="320"
              data-x="800"
              data-speed="800"
              data-start="3500"
              data-easing="Power4.easeOut"
              data-endspeed="300"
              data-endeasing="Power1.easeIn"
              data-captionhidden="off">
              <span class="page-scroll"><a href="single_product.html" class="btn primary-btn">Buy Now<i class="glyphicon glyphicon-chevron-right"></i></a></span>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/home/_featured_collection.html.erb
<div class="row featuredCollection">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>人気カテゴリー</h4>
    </div>
  </div>
  <div class="col-sm-4 col-xs-12">
    <div class="thumbnail" onclick="location.href='single_product.html';">
      <div class="imageWrapper">
        <%= image_tag("home/featured-collection/featured-collection-01.jpg", :alt => "feature-collection-image") %>
        <div class="masking"><a href="product_grid_left_sidebar.html" class="btn viewBtn">View Shirts</a></div>
      </div>
      <div class="caption">
        <h4>Shirts</h4>
      </div>
    </div>
  </div>
  <div class="col-sm-4 col-xs-12">
    <div class="thumbnail" onclick="location.href='single_product.html';">
      <div class="imageWrapper">
        <%= image_tag("home/featured-collection/featured-collection-02.jpg", :alt => "feature-collection-image") %>
        <div class="masking"><a href="product_grid_left_sidebar.html" class="btn viewBtn">View Bags</a></div>
      </div>
      <div class="caption">
        <h4>Bags</h4>
      </div>
    </div>
  </div>
  <div class="col-sm-4 col-xs-12">
    <div class="thumbnail" onclick="location.href='single_product.html';">
      <div class="imageWrapper">
        <%= image_tag("home/featured-collection/featured-collection-03.jpg", :alt => "feature-collection-image") %>
        <div class="masking"><a href="product_grid_left_sidebar.html" class="btn viewBtn">View Lifestyle</a></div>
      </div>
      <div class="caption">
        <h4>Lifestyle</h4>
      </div>
    </div>
  </div>
</div>

app/views/potepan/home/_latest_articles.html.erb
<div class="row latestArticles">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>お役立ち記事</h4>
    </div>
  </div>
  <div class="col-sm-3 col-xs-12">
    <div class="thumbnail">
      <h5><a href="blog_single_left_sidebar.html">記事タイトル</a></h5>
      <span class="meta">2016/9/16</span>
      <a href="blog_single_left_sidebar.html"><%= image_tag("home/articles/articles-01.jpg", :alt => "article-image") %></a>
      <div class="caption">
        <p>記事本文（100文字）</p>
      </div>
    </div>
  </div>
  <div class="col-sm-3 col-xs-12">
    <div class="thumbnail">
      <h5><a href="blog_single_left_sidebar.html">記事タイトル</a></h5>
      <span class="meta">2016/9/16</span>
      <a href="blog_single_left_sidebar.html"><%= image_tag("home/articles/articles-02.jpg", :alt => "article-image") %></a>
      <div class="caption">
        <p>記事本文（100文字）</p>
      </div>
    </div>
  </div>
  <div class="col-sm-3 col-xs-12">
    <div class="thumbnail">
      <h5><a href="blog_single_left_sidebar.html">記事タイトル</a></h5>
      <span class="meta">2016/9/16</span>
      <a href="blog_single_left_sidebar.html"><%= image_tag("home/articles/articles-03.jpg", :alt => "article-image") %></a>
      <div class="caption">
        <p>記事本文（100文字）</p>
      </div>
    </div>
  </div>
  <div class="col-sm-3 col-xs-12">
    <div class="thumbnail">
      <h5><a href="blog_single_left_sidebar.html">記事タイトル</a></h5>
      <span class="meta">2016/9/16</span>
      <a href="blog_single_left_sidebar.html"><%= image_tag("home/articles/articles-04.jpg", :alt => "article-image") %></a>
      <div class="caption">
        <p>記事本文（100文字）</p>
      </div>
    </div>
  </div>
</div>

app/views/potepan/home/_new_arrivals_products.html.erb
<div class="row featuredProducts">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>新着商品</h4>
    </div>
  </div>
  <div class="col-xs-12">
    <div class="owl-carousel featuredProductsSlider">
      <%= render partial: 'product', collection: @new_arrivals_products %>
    </div>
  </div>
</div>

app/views/potepan/home/_product.html.erb
<div class="slide">
  <div class="productImage clearfix">
    <% if product.images.any? %>
      <%= image_tag product.images.first.attachment.url %>
    <% else %>
      <%= image_tag("img/products/products-01.jpg", :alt => "products-img") %>
    <% end %>
    <div class="productMasking">
      <ul class="list-inline btn-group" role="group">
        <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
        <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
        <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-eye"></i></a></li>
      </ul>
    </div>
  </div>
  <div class="productCaption clearfix">
    <%= link_to potepan_product_path(product.id) do %>
      <h5><%= product.name %></h5>
    <% end %>
    <h3><%= product.display_price %></h3>
  </div>
</div>

app/views/potepan/home/index.html.erb
<% provide(:title, 'BIGBAG Store') %>

<!-- BANNER -->
<%= render 'banner' %>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <%= render 'featured_collection' %>
    <% if @new_arrivals_products.any? %>
      <%= render 'new_arrivals_products' %>
    <% end%>
    <%= render 'latest_articles' %>
  </div>
</section>

<%= render 'shared/partners_logo' %>

<% content_for :product_quick_view_modal do %>
  <%= render 'shared/product_quick_view_modal'%>
<% end %>

app/views/potepan/products/_breadcrumb_nav.html.erb
<% if @option_value_color.nil? %>
  <% if params[:color].present? %>
    <%= render partial: 'shared/main_nav_bar', locals: { page_title: "ERROR",
                                                         path_second: true,
                                                         page_active: "ERROR" } %>
  <% else %>
    <%= render partial: 'shared/main_nav_bar', locals: { page_title: "ALL",
                                                         path_second: true,
                                                         page_active: "ALL" } %>
  <% end %>
<% else %>
  <%= render partial: 'shared/main_nav_bar', locals: { page_title: @option_value_color.name,
                                                       path_second: true,
                                                       page_active: @option_value_color.name } %>
<% end %>

app/views/potepan/products/_carousel_image.html.erb
<div id="carousel" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <% if @product.images.any? %>
      <% @product.images.each_with_index do |img, i| %>
        <div class="item <% if product_main_image_active?(i, @variant_number) %>active<% end %>" data-thumb="<%= i %>">
          <%= image_tag img.attachment.url(:product) %>
        </div>
      <% end %>
    <% else %>
      <div class="item" data-thumb="0">
        <%= image_tag("img/products/signle-product/product-slide-big-01.jpg") %>
      </div>
    <% end %>
    <% unless @variant_number.nil? %>
      <% @variants.images.each_with_index do |img, i| %>
        <div class="item <% if i.zero? %>active<% end %>" data-thumb="<%= product_thumb_image_number(i, @product.images.size) %>">
          <%= image_tag img.attachment.url(:product) %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<div class="clearfix">
  <div id="thumbcarousel" class="carousel slide" data-interval="false">
    <div class="carousel-inner">
      <% if @product.images.any? %>
        <% @product.images.each_with_index do |img, i| %>
          <div data-target="#carousel" data-slide-to="<%= i %>" class="thumb">
            <%= image_tag img.attachment.url(:product) %>
          </div>
        <% end %>
      <% else %>
        <div data-target="#carousel" data-slide-to="0" class="thumb">
          <%= image_tag("img/products/signle-product/product-slide-small-01.jpg") %>
        </div>
      <% end %>
      <% unless @variant_number.nil? %>
        <% @variants.images.each_with_index do |img, i| %>
          <div data-target="#carousel" data-slide-to="<%= product_thumb_image_number(i, @product.images.size) %>" class="thumb">
            <%= image_tag img.attachment.url(:product) %>
          </div>
        <% end %>
      <% end %>
    </div>
    <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
  </div>
</div>

app/views/potepan/products/_related_products.html.erb
<div class="row productsContent">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>関連商品</h4>
    </div>
  </div>
  <% if products.any? %>
    <%= render partial: 'shared/product', collection: products, locals: { class_name: 'col-md-3 col-sm-6 col-xs-12' } %>
  <% else %>
    <div class="col-xs-12">
      <p>関連商品はありません。</p>
    </div>
  <% end %>
</div>

app/views/potepan/products/_sidebar.html.erb
<div class="col-md-3 col-sm-4 col-xs-12 sideBar">
  <%= render 'shared/sidebar_categories', taxonomies: @taxonomies, active_taxon_id: nil %>
  <%= render 'shared/sidebar_search_price' %>
  <% if @option_value_color.nil? %>
    <%= render 'shared/sidebar_search_color', search_colors: @search_colors, active_color_name: nil %>
  <% else %>
    <%= render 'shared/sidebar_search_color', search_colors: @search_colors, active_color_name: @option_value_color.name %>
  <% end %>
  <%= render 'shared/sidebar_search_size' %>
</div>

app/views/shared/_head.html.erb
<%= csrf_meta_tags %>
<title><%= full_title page_title: yield(:title) %></title>
<!-- PLUGINS CSS STYLE -->
<%= stylesheet_link_tag 'application', :media => "all" %>

<!-- GOOGLE FONT -->
<%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>

<!-- CUSTOM CSS -->

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/shared/_script.html.erb
<%= javascript_include_tag 'application' %>

app/views/shared/_sidebar_categories.html.erb
<div class="panel panel-default">
  <div class="panel-heading">商品カテゴリー</div>
  <div class="panel-body">
    <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
      <ul class="nav navbar-nav side-nav">
        <% taxonomies.each do | taxonomy | %>
          <li>
            <a href="javascript:;" data-toggle="collapse" data-target="#js-side-accordion<%= taxonomy.id %>">
              <%= taxonomy.name %>
              <i class="fa fa-plus"></i>
            </a>
            <ul id="js-side-accordion<%= taxonomy.id %>" class="collapse collapseItem">
              <% taxonomy.taxons.each do |taxon| %>
                <li>
                  <%= link_to potepan_category_path(taxon.id), class: active_taxon_id == taxon.id ? 'active' : nil  do %>
                    <i class="fa fa-caret-right" aria-hidden="true"></i>
                    <%= taxon.name %> <% unless taxon.leaf? %>All<% end %>
                    <span>(<%= taxon.products_quantity %>)</span>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_sidebar_search_color.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">色から探す</div>
  <div class="panel-body">
    <ul class="list-unstyled">
      <% search_colors.each do | color | %>
        <li>
          <%= link_to potepan_products_path(color: "#{color.name}"), class: active_color_name == color.name ? 'active' : nil do %>
            <%= color.name %><span><%= "(#{color.variants.count})" %></span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>